/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Biblioteca;

import logica.ControladorVentanas;
import persistencia.ConexionBD;

public class App {

    public static void main(String[] args) {
        ConexionBD.inicializar();
        ControladorVentanas.iniciar();
    }
}
