/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Biblioteca;

import logica.ControladorVentanas;
import modelo.Autor;
import modelo.Libro;
import modelo.Tema;
import persistencia.ConexionBD;
import persistencia.LibroDAO;

public class App {

    public static void main(String[] args) {
        ConexionBD.obtenerConexion();
        ConexionBD.inicializar();
        //ControladorVentanas.iniciar();
        Libro l1 = new Libro("harry potter y la paja eterna", "Porno", 69, Tema.COMEDIA, new Autor("mipadre",37001));
        LibroDAO.insertarLibro(l1);
 
    }
}
