/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Biblioteca;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme;
import logica.ControladorPrincipal;
import vista.VentanaCliente;
import vista.VentanaInicioSesion;

public class App {

    public static void main(String[] args) {
        FlatMaterialDeepOceanIJTheme.setup();
        //ControladorPrincipal.iniciar();
        VentanaInicioSesion vl = new VentanaInicioSesion();
        vl.setVisible(true);
        vl.setLocationRelativeTo(null);
    }
}
